### ISSUE TITLE
Migrate travis-ci .org -> .com

### ISSUE THREAD

**Issue by adam-cattermole** [striot/striot#100]
It looks like we're using travis-ci.org, and this is becoming legacy as they are moving all repositories to travis-ci.com. Migration is only in beta for public repositories within organisations, but currently, it [is not working](https://travis-ci.community/t/cannot-migrate-repository/8110). Once it's back up and running again it is probably worth migrating to the new one.

**Comment by adam-cattermole** [comment]
Now this has been fixed I have attempted to migrate to travis-ci.com. Going to leave this issue open until confirmed working as intended.

**Comment by jmtd** [comment]
It seems to be! I've just updated the badge URI.
