### ISSUE TITLE
Travis builds broken since merging TH changes

### ISSUE THREAD

**Issue by jmtd** [striot/striot#105]

**Comment by adam-cattermole** [comment]
I noticed this the other day - I've seen this error before, it was because of htfpp struggling to parse non-ascii characters in the files.

**Comment by adam-cattermole** [comment]
Ahh I didn't spot this in the PR before last time I looked - it's the ellipsis symbol here I think https://github.com/striot/striot/pull/104/files#diff-45684f9ff30e8e4c9ba3259b4946c6caR281

**Comment by jmtd** [comment]
Thanks - I realise we've hit this before. I need to stop typing ellipses, and/or fix htfpp :)
