### ISSUE TITLE
pipeline example eventually fails

### ISSUE THREAD

**Issue by jmtd** [striot/striot#13]
If I run the pipeline example, I eventually get

```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

**Comment by adam-cattermole** [comment]
Do you have an idea of how long you ran it for to obtain this output?

**Comment by PaulWatson9994** [comment]
Adam, would it be possible to repeat the experiment without a link node? (with the stream processing function of client2 - streamMap (\st-> reverse st) - moved into the sink so that the same stream processing pipeline is being executed.. but only in 2 containers?). It makes the configuration simpler, and could help us find out if it's the link node that's the problem, Paul

**Comment by jmtd** [comment]
> Do you have an idea of how long you ran it for to obtain this output?

I think approximately a minute, corresponding to the default COMPOSE_HTTP_TIMEOUT value, but I'm not certain. Re-running to check.

(I hit this, by the way, before or after PR #12, so it wasn't caused by that)

**Comment by jmtd** [comment]
The issue is the `tty: true` for the link node. This causes docker compose to expect log messages from the node, and when it doesn't see any, it thinks there's a fault and kills all three nodes.

**Comment by adam-cattermole** [comment]
> Adam, would it be possible to repeat the experiment without a link node? (with the stream processing function of client2 - streamMap (\st-> reverse st) - moved into the sink so that the same stream processing pipeline is being executed.. but only in 2 containers?). It makes the configuration simpler, and could help us find out if it's the link node that's the problem, Paul

@PaulWatson9994 I'm assuming these comments are related to the throughput testing notes in PR #12? I'll create a new issue with the information from that PR and respond there.
