### ISSUE TITLE
"id" field in Event type

### ISSUE THREAD

**Issue by jmtd** [striot/striot#3]
`FunctionalIoTypes.Event` has an `id` field. However we have not updated the README to reflect this. It also clashes with `Prelude.id`, which could be awkward. We should re-evaluate whether we require the field at all, and if so, consider renaming it (or encouraging the qualified import of Striot).

**Comment by PaulWatson9994** [comment]
We added this when we were thinking about ways to capture the provenance of IoT computations: having a unique id for each event seems a good starting point. We also thought it might be useful for performance tracing .. e.g. to measure how long it took for an event to be processed through a pipeline(though windowing adds a complication). However, we don't use them at the moment. Perhaps we should see if they prove useful over the coming months, and if not then we could remove them.

Either way, perhaps we should rename to avoid the prelude clash.
