### ISSUE TITLE
Update to newer version of Haskell/GHC

### ISSUE THREAD

**Issue by adam-cattermole** [striot/striot#33]
We are currently building our solution against GHC 8.0.1, which is over two years old (there are 9 subsequent stable releases). It may be worth upgrading to a newer version to avoid difficulty transitioning at a later stage.

This will require updating all packages and dependencies, and fixing any deprecation issues.

@jmtd do you think this would be a good idea?

**Comment by adam-cattermole** [comment]
An alternative would be to use `:8` so that we also get the minor fixes, but we can handle the major change from 8 → 9 manually.

**Comment by jmtd** [comment]
I realised I assumed GHC was using semantic versioning, but [this is the GHC version policy](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/intro.html#ghc-version-numbering-policy). I think I vote for `8.4` and we do some manual work to move to each new release.

BTW, have you ever used stack or stackage? I haven't, (I haven't used cabal's sandbox feature either), but they look potentially useful. I think I've hit one dependency-hell situation so far.

**Comment by adam-cattermole** [comment]
Sure, I'll test with `8.4` and see if I run into any issues.

I use stack when building the solution on VM's as it seems a little easier to install and get everything set up. That being said, it can sometimes get into a state with dependency conflicts, and isn't always easy to solve.

I use Cabal sandboxes for small snippets of test code, as you can easily install the Striot package and any others in a localised way. That being said I noticed that sandboxes aren't part of the cabal v2 commands, and that the newer version of cabal installs packages in a different way to before, so may be worth investigating a little.
