### ISSUE TITLE
streamScan base case behaviour

### ISSUE THREAD

**Issue by adam-cattermole** [striot/striot#38]
I am trying to get my head around the base case behaviour of `streamScan`. Can anyone explain why it is that we emit a final `Event`, repeating the final value of the accumulator in the base case when we reach the empty list `[]`?

For example, if my aggregation is simply a summation of a `Stream Int`, with input of `[2,5,8]` and `acc` value of 0, I will get `[2,7,15,15]` rather than `[2,7,15]`. The last value is the final value of the accumulator repeated, without a `time` - the old `V` `Event` type.

**Comment by adam-cattermole** [comment]
I just saw the implementation of [scanl](http://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.List.html#scanl) for lists does not replicate this behaviour, so it is likely a mistake (`scanl (+) 0 [2,5,8] = [0,2,7,15]`).

This behaviour would not be seen while we are working on infinite lists but just in case I'll put in a fix.

**Comment by PaulWatson9994** [comment]
It does sound like I introduced a bug Adam. Please do fix it

Paul

Regards
Paul

________________________________

**Comment by jmtd** [comment]
> The fix looks good, I'm hoping to write a small test case before/after merging it to show the fix working

I wrote a test case, proved it failed before and passed after this PR, so I'm happy for it to be merged. I'll push the test case in another PR.
