### ISSUE TITLE
Monitoring of the deployment

### ISSUE THREAD

**Issue by adam-cattermole** [striot/striot#59]
At the moment it is pretty difficult to work out what is going on in the streaming system, due to a lack of monitoring. I plan to implement a solution using [prometheus](https://hackage.haskell.org/package/prometheus) soon, allowing us to route to a web endpoint that is displaying useful information.

I am hoping that I will be able to list ingress/egress total number of events, total bytes, along with number of accepted connections. This gives us a quick way to debug the system, and we can then use the prometheus solution to scrape these endpoints for realtime monitoring, which should help us make dynamic changes to the infrastructure.

If there are any additional metrics that you think would be useful, let me know and I can see if I can implement them. Perhaps some sort of latency measure would be useful also, but I will try to bear in mind that the metrics could influence performance quite heavily.

**Comment by jmtd** [comment]
This sounds very useful, thanks. One thing I had been discussing as  a possible future feature of the Optimizer would be to rewrite graphs to introduce additional opportunities for gathering data about stuff in-flight: adding "taps" so you could monitor the events flowing between operators within a node. But it's just a pipe dream at the moment, and the operators we have at the moment probably proclude it (if I looked at this, it might also have been looking at introducing new operators that acted like inverse-merges: i.e., split a stream into two outbound streams, one the normal one, the other for diagnosis purposes.)

**Comment by adam-cattermole** [comment]
> One thing I had been discussing as a possible future feature of the Optimizer would be to rewrite graphs to introduce additional opportunities for gathering data about stuff in-flight: adding "taps" so you could monitor the events flowing between operators within a node

This sounds really cool.

> i.e. split a stream into two outbound streams, one the normal one, the other for diagnosis purposes

This is something I have also been thinking about, and something we will definitely need at some point. The notion of duplicating the stream to two different endpoints would be key to merging our system with the sort of stuff that George is working on in fault tolerance.
