### ISSUE TITLE
travis: run test suite on every PR

### ISSUE THREAD

**Issue by jmtd** [striot/striot#81]
./gen_test_makefile.sh > Makefile; make; ./gen_test_makefile.sh > Makefile; make and to build and run TestMain

**Comment by adam-cattermole** [comment]
I think `TestMain` should already be run as Travis is configured to run the test-suite with:

`cabal configure --enable-tests && cabal build && cabal test`

Good idea though, we should add the check to ensure the examples are building correctly also.
